// Mock data for frontend development and offline testing
// References models in src/types/index.ts and specs in .agents/SPECS.md

import type { Post, Lesson, Subject, Level, Tag, UserPublic } from "@/types";

export const MOCK_SUBJECTS: Subject[] = [
  { id: "sub-math", code: "MATH", name: "Mathematics" },
  { id: "sub-cs", code: "CS", name: "Computer Science" },
  { id: "sub-phys", code: "PHYS", name: "Physics" },
  { id: "sub-chem", code: "CHEM", name: "Chemistry" },
  { id: "sub-bio", code: "BIO", name: "Biology" },
];

export const MOCK_LEVELS: Level[] = [
  { id: "lvl-beg", name: "Beginner", order: 1 },
  { id: "lvl-int", name: "Intermediate", order: 2 },
  { id: "lvl-adv", name: "Advanced", order: 3 },
];

export const MOCK_TAGS: Tag[] = [
  { id: "tag-calc", name: "calculus" },
  { id: "tag-py", name: "python" },
  { id: "tag-algo", name: "algorithms" },
  { id: "tag-quant", name: "quantum" },
  { id: "tag-org", name: "organic" },
  { id: "tag-ds", name: "data-structures" },
  { id: "tag-ai", name: "ai" },
  { id: "tag-gen", name: "general" },
];

export const MOCK_USERS: Record<string, UserPublic> = {
  admin: {
    id: "user-admin",
    clerk_id: "user_admin_e2e",
    display_name: "Admin User",
    profile_image_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Admin",
    role: "ADMIN",
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    bio: "Platform Administrator & Moderator",
  },
  creator1: {
    id: "user-creator1",
    clerk_id: "user_creator1_e2e",
    display_name: "Creator Alice",
    profile_image_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alice",
    role: "CREATOR",
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    bio: "CS Educator specializing in Algorithms and Systems Architecture.",
  },
  creator2: {
    id: "user-creator2",
    clerk_id: "user_creator2_e2e",
    display_name: "Creator Bob",
    profile_image_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Bob",
    role: "CREATOR",
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    bio: "Physics & Mathematics instructor. Making deep topics accessible.",
  },
  student1: {
    id: "user-student1",
    clerk_id: "user_student1_e2e",
    display_name: "Student Charlie",
    profile_image_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Charlie",
    role: "STUDENT",
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    bio: "Aspiring software engineer exploring machine learning and algorithms.",
  },
  student2: {
    id: "user-student2",
    clerk_id: "user_student2_e2e",
    display_name: "Student Diana",
    profile_image_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Diana",
    role: "STUDENT",
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    bio: "Undergrad student passionate about math and physics.",
  },
};

export const MOCK_POSTS: Post[] = [
  {
    id: "post-1",
    author: MOCK_USERS.student1.id,
    author_details: MOCK_USERS.student1,
    post_type: "QUESTION",
    title: "How to understand gradient descent intuitively?",
    body: "I'm learning machine learning fundamentals and gradient descent feels abstract with all the partial derivatives. Can anyone provide an intuitive geometric or physical analogy?",
    subject: MOCK_SUBJECTS[1].id,
    subject_details: MOCK_SUBJECTS[1],
    level: MOCK_LEVELS[0].id,
    level_details: MOCK_LEVELS[0],
    attachment_url: null,
    tags_data: [MOCK_TAGS[1], MOCK_TAGS[2], MOCK_TAGS[6]],
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    vote_count: 8,
    comment_count: 4,
    user_vote: null,
  },
  {
    id: "post-2",
    author: MOCK_USERS.student2.id,
    author_details: MOCK_USERS.student2,
    post_type: "QUESTION",
    title: "Geometric interpretation of Eigenvalues and Eigenvectors",
    body: "When a matrix acts on a vector, most vectors change direction. But eigenvectors only scale! What are the best visual examples for understanding principal directions?",
    subject: MOCK_SUBJECTS[0].id,
    subject_details: MOCK_SUBJECTS[0],
    level: MOCK_LEVELS[1].id,
    level_details: MOCK_LEVELS[1],
    attachment_url: null,
    tags_data: [MOCK_TAGS[0], MOCK_TAGS[7]],
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    vote_count: 5,
    comment_count: 2,
    user_vote: null,
  },
  {
    id: "post-3",
    author: MOCK_USERS.creator1.id,
    author_details: MOCK_USERS.creator1,
    post_type: "SHARING",
    title: "Curated Guide: Mastering Data Structures in 2026",
    body: "Over the past 5 years teaching CS, I've compiled the key patterns: Two Pointers, Sliding Window, Monotonic Stacks, and Union-Find. Here is a breakdown of how to identify which pattern applies to any problem.",
    subject: MOCK_SUBJECTS[1].id,
    subject_details: MOCK_SUBJECTS[1],
    level: MOCK_LEVELS[1].id,
    level_details: MOCK_LEVELS[1],
    attachment_url: null,
    tags_data: [MOCK_TAGS[5], MOCK_TAGS[2], MOCK_TAGS[1]],
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    vote_count: 19,
    comment_count: 6,
    user_vote: 1,
  },
  {
    id: "post-4",
    author: MOCK_USERS.admin.id,
    author_details: MOCK_USERS.admin,
    post_type: "ANNOUNCEMENT",
    title: "Welcome to the E2E Platform — Community Guidelines",
    body: "Welcome to E2E! Please follow our community rules: Be respectful, tag your posts appropriately with subjects and levels, and provide constructive peer answers.",
    subject: MOCK_SUBJECTS[1].id,
    subject_details: MOCK_SUBJECTS[1],
    level: MOCK_LEVELS[0].id,
    level_details: MOCK_LEVELS[0],
    attachment_url: null,
    tags_data: [MOCK_TAGS[7]],
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    vote_count: 42,
    comment_count: 3,
    user_vote: null,
  },
];

export const MOCK_LESSONS: Lesson[] = [
  {
    id: "lesson-1",
    author: MOCK_USERS.creator1.id,
    author_details: MOCK_USERS.creator1,
    state: "PUBLISHED",
    title: "Introduction to Dynamic Programming: Memoization vs Tabulation",
    body: "Dynamic Programming (DP) is simply recursion without doing repeated work. In this lesson, we will explore both Top-Down (Memoization) and Bottom-Up (Tabulation) approaches using classic problems like Fibonacci, Coin Change, and the 0/1 Knapsack problem.",
    subject: MOCK_SUBJECTS[1].id,
    subject_details: MOCK_SUBJECTS[1],
    level: MOCK_LEVELS[1].id,
    level_details: MOCK_LEVELS[1],
    embedded_video_url: "https://www.youtube.com/watch?v=oBt53YbR9Kk",
    attachments: [],
    tags: ["algorithms", "python", "data-structures"],
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    vote_count: 35,
    user_vote: 1,
  },
  {
    id: "lesson-2",
    author: MOCK_USERS.creator2.id,
    author_details: MOCK_USERS.creator2,
    state: "PUBLISHED",
    title: "Calculus I: Limits and Continuity from Scratch",
    body: "Before understanding derivatives, we must build a rock-solid grasp of limits. We start with intuitive tables of values, then move to algebraic evaluation techniques (factoring, conjugate rationalization, and the squeeze theorem).",
    subject: MOCK_SUBJECTS[0].id,
    subject_details: MOCK_SUBJECTS[0],
    level: MOCK_LEVELS[0].id,
    level_details: MOCK_LEVELS[0],
    embedded_video_url: "https://www.youtube.com/watch?v=WUvTyaaNkzM",
    attachments: [],
    tags: ["calculus"],
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    vote_count: 22,
    user_vote: null,
  },
];
